name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up git
        run: |
          git config user.name "Daniel-lam1702"
          git config user.email "daniellam1702@tamu.edu"

      - name: Add upstream
        run: git remote add upstream https://github.com/CSCE331-Fall2024/project-3-team-5b.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Checkout main branch
        run: git checkout main

      - name: Merge upstream changes
        run: |
          git merge upstream/main --allow-unrelated-histories || true
          git checkout --theirs . # Keep upstream changes in all files
          git add . # Stage all changes

      - name: Commit merge
        run: git commit -m "Auto-resolved merge conflicts by keeping upstream changes" || true

      - name: Push changes
        run: git push origin main --force
